.TH test.sh
.SH NAME
_printf \- Prints Text
.SH SYNOPSIS
.B _printf OPTION
.SH DESCRIPTION
.B test.sh
This is a function that prints diffent things depending on which option has been chosen.
.SH OPTIONS
.TP
.BR c
Prints a single character.
.TP
.BR s
Prints a string of characters.
.TP
.BR %
Prints the "%" symbol.
.TP
.BR d
Prints a decimal number.
.TP
.BR i
Prints an integer in base 10.
